sudo: false
language: scala
dist: trusty
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
script:
- git clone https://github.com/gitbucket/gitbucket.git
- cd gitbucket
- sbt publishLocal
- cd ../
- sbt test